version: '3'
services:    
  db:
    image: postgres
    ports: 
      - '5432'
    env_file: 
      - variables.env   
    environment: 
      - POSTGRES_DB=team_manager
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8990
    volumes:
      - .:/team_manager
    ports:
      - "8990:8990"
    depends_on: 
       - db
    env_file: 
      - variables.env      